# Numpy


NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is highly efficient, mainly due to its use of compiled C code.

NumPy is like a supercharged toolbox for handling numbers and doing math in Python. It's a library that makes it easier and faster to work with large sets of data, especially when you're dealing with numbers.

# Why do we use NumPy?


Efficiency: NumPy is super fast because it's written in a language called C, which is really good at crunching numbers quickly. This means you can do complex math operations on huge amounts of data without waiting forever.

Arrays: NumPy gives us a cool new data type called arrays. Think of arrays like fancy lists that can hold lots of numbers in a nice, organized way. Arrays make it easy to do math on whole sets of data all at once.

Math Functions: NumPy comes with tons of built-in math functions that work with arrays. Need to add up a bunch of numbers? NumPy's got you covered. Want to find the average of a set of values? NumPy can do that too, and much more!

# How do we use NumPy?


Install NumPy: First, you need to install NumPy on your computer. You can do this using a tool called pip, which comes with Python. Just type pip install numpy in your command prompt or terminal.

Import NumPy: Once NumPy is installed, you can start using it in your Python programs. You do this by typing import numpy as np at the top of your code. This tells Python that you want to use NumPy and that you'll refer to it as np to save typing.

Create Arrays: Now that NumPy is ready to go, you can create arrays using the np.array() function. You just pass in a list of numbers, and NumPy will turn it into an array for you.

Do Math: With your arrays all set up, you can start doing math with them! NumPy lets you add, subtract, multiply, and divide arrays just like you would with regular numbers.

Explore: NumPy has lots of other cool features too, like slicing and indexing arrays, reshaping them, and even fancy stuff like Fourier transforms. The more you explore, the more you'll discover what NumPy can do!

<br><br>

1. **Data Type**:
   - **List**: Can store different data types in a single list.
   - **Numpy Array**: Stores elements of the same data type for more efficient computation.
<br><br><br>
2. **Performance**:
   - **List**: Slower for numerical operations due to generic data type handling.
   - **Numpy Array**: Faster for numerical operations due to optimized C-based implementation.

<br><br>
3. **Functionality**:
   - **List**: Limited built-in functions for numerical operations.
   - **Numpy Array**: Rich set of built-in functions for complex numerical operations.

<br><br>
4. **Memory Usage**:
   - **List**: Consumes more memory as it stores both data and type information.
   - **Numpy Array**: More memory-efficient, storing only data with uniform type.

<br><br>
5. **Broadcasting**:
   - **List**: Does not support broadcasting; element-wise operations require explicit loops.
   - **Numpy Array**: Supports broadcasting, allowing element-wise operations without explicit loops.


In [ ]:
# pip install numpy

In [1]:
 import numpy as np

In [2]:
np.__version__

'1.23.5'

In [3]:
a=[2,3,5,5,666,463]
print(a+2)

[2, 3, 5, 5, 666, 463, 2, 3, 5, 5, 666, 463]


In [4]:
a=[1,2,3,4,5,6,7,8,9,10]

In [5]:
array = np.array(a)
print(array,type(array),id(array))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'> 2920668165872


In [6]:
print(array*2)

[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
array.ndim

1

In [8]:
array.shape

(10,)

In [9]:
array.size

10

In [10]:
a={1,2,3,4,5,6,7,8,9,10}
array = np.array(a)
print(array,type(array),id(array))

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10} <class 'numpy.ndarray'> 2920693696432


In [11]:
a={1,2,3,4,5,6,"Hello",8,9,True}
array = np.array(a)
print(array,type(array),id(array))

{1, 2, 3, 4, 5, 6, 8, 9, 'Hello'} <class 'numpy.ndarray'> 2920693697104


In [12]:
a=[[1,2,3],[4,5,6],[7,8,9]]

val = np.array(a)
print(val)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
val.ndim

2

In [14]:
val.shape

(3, 3)

In [15]:
val.size

9

In [16]:
a={1,2,3}
print(a*2)

TypeError: unsupported operand type(s) for *: 'set' and 'int'

In [17]:
a= range(20,40)
result = np.array(a)
print(result)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [19]:
value = np.arange(20,30,2,dtype=float)
print(value,type(value))

[20. 22. 24. 26. 28.] <class 'numpy.ndarray'>


In [22]:
ones  = np.ones((3,3),dtype=int)
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [23]:
zero  = np.zeros((3,3),dtype=int)
print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
eye = np.eye(3,dtype=int)
print(eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [28]:
diag = np.diag((1,2,3))
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [27]:
array = np.random.randint(2,12,(3,3),dtype=int)
print(array)

[[ 8 11 10]
 [ 6  6  9]
 [10  4  4]]


In [30]:
equal = np.linspace(10,100,10)
print(equal)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [31]:
equal = np.linspace(12,33,10)
print(equal)

[12.         14.33333333 16.66666667 19.         21.33333333 23.66666667
 26.         28.33333333 30.66666667 33.        ]


In [32]:
array = np.random.randint(2,12,(3,3),dtype=int)
print(array)

[[10  6  5]
 [ 2 10  9]
 [ 2 10 11]]


In [35]:
array[0]

array([10,  6,  5])

In [36]:
array[-2]

array([ 2, 10,  9])

In [37]:
array[2][1]

10

In [39]:
array[1][2]=100

In [40]:
array

array([[ 10,   6,   5],
       [  2,  10, 100],
       [  2,  10,  11]])

In [43]:
array[[0,1]]

array([[ 10,   6,   5],
       [  2,  10, 100]])

In [42]:
array[[1,2]]

array([[  2,  10, 100],
       [  2,  10,  11]])

In [33]:
[array % 2 == 0]

[array([[ True,  True, False],
        [ True,  True, False],
        [ True,  True, False]])]

In [34]:
array[array % 2 == 0]

array([10,  6,  2, 10,  2, 10])

In [44]:
array = np.random.randint(2,12,(4,4),dtype=int)
print(array)

[[ 4 10 10  9]
 [10  5 11  8]
 [ 2  2  2 11]
 [ 5  7  5  5]]


In [46]:
array.sum()

106

In [47]:
print(sum(array))

[21 24 28 33]


In [49]:
np.sum(array,axis=1)

array([33, 34, 17, 22])

In [51]:
array1 = np.random.randint(2,12,(2,2),dtype=int)
print(array1)

[[11  7]
 [ 4  5]]


In [52]:
array2 = np.random.randint(2,12,(2,2),dtype=int)
print(array2)

[[ 3  7]
 [10  5]]


In [53]:
print(array1 * array2)

[[33 49]
 [40 25]]


In [54]:
result = array1.dot(array2)
print(result)

[[103 112]
 [ 62  53]]


In [55]:
np.mean(result)

82.5

In [56]:
np.median(result)

82.5

In [57]:
array = np.random.randint(2,12,(3,3),dtype=int)
print(array)

[[ 4  5  2]
 [ 2  7 11]
 [ 6  3  4]]


In [58]:
np.sqrt(array)

array([[2.        , 2.23606798, 1.41421356],
       [1.41421356, 2.64575131, 3.31662479],
       [2.44948974, 1.73205081, 2.        ]])

In [59]:
np.std(array)

2.6851213274654606

In [60]:
np.average(array)

4.888888888888889

In [61]:
np.mean(array)

4.888888888888889

In [63]:
comman = np.full((3,3),4)
print(comman)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [64]:
array

array([[ 4,  5,  2],
       [ 2,  7, 11],
       [ 6,  3,  4]])

In [69]:
max = np.max(array)
print(max)

11


In [70]:
armax = np.argmax(array)
print(armax)

5


In [71]:
result = np.sort(array)
print(result)

[[ 2  4  5]
 [ 2  7 11]
 [ 3  4  6]]


In [72]:
result = np.sort(array,axis = 0)
print(result)

[[ 2  3  2]
 [ 4  5  4]
 [ 6  7 11]]


In [76]:
array

array([[ 4,  5,  2],
       [ 2,  7, 11],
       [ 6,  3,  4]])

In [75]:
sort = np.argsort(array)
print(sort)

[[2 0 1]
 [0 1 2]
 [1 2 0]]


In [79]:
result = np.append(array,[2,3,4],axis=0)
print(result)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [85]:
array = np.random.randint(2,12,(3,3),dtype=int)
print(array)

[[ 4  4  5]
 [11  5  4]
 [ 3  4  5]]


In [83]:
flat = np.ravel(array)
print(flat)

[ 2  4 10 10  2  4  4 10  3]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = np.reshape(arr, (2, 3))
print(arr_reshaped)


[[1 2 3]
 [4 5 6]]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
transposed_arr = np.transpose(arr)
print(transposed_arr)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_arr = np.vstack((a, b))
print(stacked_arr)


[[1 2 3]
 [4 5 6]]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_arr = np.hstack((a, b))
print(stacked_arr)


[1 2 3 4 5 6]


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concatenated_arr = np.concatenate((a, b))
print(concatenated_arr)





[1 2 3 4 5 6]


In [13]:
a2 = np.array([[1, 2], [3, 4]])
b2 = np.array([[5, 6], [7, 8]])
concatenated_arr2 = np.concatenate((a2, b2), axis=0)
print(concatenated_arr2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
a2 = np.array([[1, 2], [3, 4]])
b2 = np.array([[5, 6], [7, 8]])
concatenated_arr2 = np.concatenate((a2, b2), axis=1)
print(concatenated_arr2)

[[1 2 5 6]
 [3 4 7 8]]


In [16]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique_elements = np.unique(arr)
print(unique_elements)


[1 2 3 4]


In [17]:
# Creating an array and using where to replace values
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.where(arr > 3, arr, -1)
print(new_arr)


[-1 -1 -1  4  5]


In [18]:
arr = np.array([1, 2, 3, 4, 5])
cumsum_arr = np.cumsum(arr)
print(cumsum_arr)


[ 1  3  6 10 15]


In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
matmul_result = np.matmul(a, b)
print(matmul_result)


[[19 22]
 [43 50]]


In [20]:

a = np.array([[1, 2], [3, 4]])
inv_a = np.linalg.inv(a)
print(inv_a)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
cov_matrix = np.cov(x, y)
print(cov_matrix)


[[ 1. -1.]
 [-1.  1.]]


In [23]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])
corr_matrix = np.corrcoef(x, y)
print(corr_matrix)


[[ 1. -1.]
 [-1.  1.]]


In [24]:
data = np.array([1, 2, 2, 3, 4, 4, 4, 5])
hist, bin_edges = np.histogram(data, bins=4)
print("Histogram:", hist)
print("Bin edges:", bin_edges)


Histogram: [1 2 1 4]
Bin edges: [1. 2. 3. 4. 5.]


In [26]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_arr = np.flip(arr)
print(flipped_arr)


[[6 5 4]
 [3 2 1]]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
trace_value = np.trace(arr)
print(trace_value)


15


In [28]:
# Extracting the diagonal of an array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal = np.diag(arr)
print(diagonal)



[1 5 9]


In [30]:
arr = np.array([1, 2, 3])
appended_arr = np.append(arr, [4, 5, 6])
print(appended_arr)


[1 2 3 4 5 6]


In [31]:
arr = np.array([1, 1, 2, 2, 2, 3])
bin_count = np.bincount(arr)
print(bin_count)


[0 2 3 1]


In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
resized_arr = np.resize(arr, (3, 2))
print(resized_arr)


[[1 2]
 [3 4]
 [5 6]]


In [33]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])
comparison = np.equal(a, b)
print(comparison)


[ True  True False]


In [34]:
arr = np.array([0, 2, 0, 3, 0, 4])
nonzero_indices = np.nonzero(arr)
print(nonzero_indices)


(array([1, 3, 5], dtype=int64),)


In [35]:
arr = np.array([1, 2, 3, 4, 5])
median_value = np.median(arr)
print(median_value)


3.0


In [36]:
arr = np.array([1, 2, 3, 4, 5])
variance = np.var(arr)
print(variance)


2.0


In [37]:
arr = np.array([1, 2, np.nan, 4, 5])
nan_check = np.isnan(arr)
print(nan_check)


[False False  True False False]
